### ISSUE TITLE
Please enter your domain/group list in noip.conf

### ISSUE THREAD

**Issue by veritas2884** [coppit/docker-no-ip#4]
# Your hostname, group name, or a comma-delimited list of a mix of them.
DOMAINS='xxxxxx.hopto.me'

This is what I have the config file set with (x's are replaced with my actual hostname) and I get this error in the logs every time I start the docker:
Please enter your domain/group list in noip.conf

Any help would be greatly appreciated!

Thank you!

**Comment by subdavis** [comment]
Issue solved:  Edit the file at location /config/dir/path, not the one it dumps in your working directory.  or specify a new path to your working directory.  This seemed like a silly design choice to me.

**Comment by coppit** [comment]
> not the one it dumps in your working directory

What "working directory" are you referring to? Do you mean the directory inside the container? The docs make no reference to any working directory, so I'm not sure what you're referring to. But it does suggest that you're not using the container as prescribed. https://hub.docker.com/r/coppit/no-ip/

The reason for having a /config/dir/path is so that your config can be externalized from the container, surviving a container destroy/create cycle (as would happen during a container upgrade). That's hardly "silly". But perhaps I'm misunderstanding you. Please clarify.

**Comment by coppit** [comment]
Closing, lacking any further information. Please reopen if you think there is an issue.
